/*
Semi-auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import type { JSX } from "react";
import * as THREE from "three";
import { type GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["chairDesk(Clone)"]: THREE.Mesh;
    Mesh_chair: THREE.Mesh;
    Mesh_chair_1: THREE.Mesh;
  };
  materials: {
    metalMedium: THREE.MeshStandardMaterial;
    carpet: THREE.MeshStandardMaterial;
  };
};

export default function Chair(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "models/chairDesk.glb",
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["chairDesk(Clone)"].geometry}
        material={materials.metalMedium}
      >
        <group position={[0.167, 0.19, -0.16]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_chair.geometry}
            material={materials.carpet}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_chair_1.geometry}
            material={materials.metalMedium}
          />
        </group>
      </mesh>
    </group>
  );
}

useGLTF.preload("models/chairDesk.glb");
