/*
Semi-auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import type { JSX } from "react";
import * as THREE from "three";
import { type GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_computerKeyboard: THREE.Mesh;
    Mesh_computerKeyboard_1: THREE.Mesh;
  };
  materials: {
    metalDark: THREE.MeshStandardMaterial;
    metalMedium: THREE.MeshStandardMaterial;
  };
};

export default function Keyboard(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "models/computerKeyboard.glb",
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_computerKeyboard.geometry}
        material={materials.metalDark}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_computerKeyboard_1.geometry}
        material={materials.metalMedium}
      />
    </group>
  );
}

useGLTF.preload("models/computerKeyboard.glb");
