/*
Semi auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { useLoader } from "@react-three/fiber";
import { type JSX, useRef } from "react";
import * as THREE from "three";
import { type GLTF } from "three-stdlib";
import useAppStore from "../../stores/useAppStore";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_computerScreen: THREE.Mesh;
    Mesh_computerScreen_1: THREE.Mesh;
  };
  materials: {
    metalDark: THREE.MeshStandardMaterial;
    metal: THREE.MeshStandardMaterial;
  };
};

export default function Monitor({
  targetRef,
  ...props
}: JSX.IntrinsicElements["group"] & {
  targetRef: React.RefObject<THREE.Mesh>;
}) {
  const screenRef = useRef<THREE.Mesh>(null!);
  const debug = useAppStore((state) => state.debug);
  const [texture] = useLoader(THREE.TextureLoader, ["./images/blahblah.png"]);

  const { nodes, materials } = useGLTF(
    "models/computerScreen.glb",
  ) as unknown as GLTFResult;

  // const cameraSpringConfigs = {
  //   visualDuration: 4.0,
  //   bounce: 0.25,
  // };
  // const cameraXSpring = useSpring(0, cameraSpringConfigs);
  // const cameraYSpring = useSpring(0, cameraSpringConfigs);
  // const cameraZSpring = useSpring(0, cameraSpringConfigs);
  // const threeCamera = useThree((state) => state.camera);

  // useEffect(() => {
  //   const unsubAnimationState = useAppStore.subscribe(
  //     (state) => state.animationState,
  //     (value, previousValue) => {
  //       if (
  //         value === "prepareToApproachMonitor" &&
  //         previousValue === "idleBoring"
  //       ) {
  //         cameraXSpring.jump(threeCamera.position.x);
  //         cameraYSpring.jump(threeCamera.position.y);
  //         cameraZSpring.jump(threeCamera.position.z);
  //         animationStateRef.current = value;
  //         cameraSpringStateRef.current = "prepareToApproachMonitor";
  //       } else if (
  //         value === "approachMonitor" &&
  //         previousValue === "prepareToApproachMonitor"
  //       ) {
  //         animationStateRef.current = value;
  //         cameraSpringStateRef.current = "approachMonitor";
  //       }
  //     },
  //   );
  //   return () => {
  //     unsubAnimationState();
  //   };
  //   // eslint-disable-next-line react-hooks/exhaustive-deps
  // }, []);

  // useFrame(({ camera }) => {
  //   if (animationStateRef.current === "prepareToApproachMonitor") {
  //     if (cameraSpringStateRef.current === "prepareToApproachMonitor") {
  //       cameraXSpring.set(0);
  //       cameraYSpring.set(1.25);
  //       cameraZSpring.set(3);
  //       cameraSpringStateRef.current = "";
  //     } else if (cameraSpringStateRef.current === "approachMonitor") {
  //       const markerWorldPosition = markerRef.current.getWorldPosition(
  //         new THREE.Vector3(),
  //       );
  //       cameraXSpring.set(camera.worldToLocal(markerWorldPosition).x);
  //       cameraYSpring.set(camera.worldToLocal(markerWorldPosition).y);
  //       cameraZSpring.set(camera.worldToLocal(markerWorldPosition).z);
  //       cameraSpringStateRef.current = "";
  //     }
  //     camera.position.set(
  //       cameraXSpring.get(),
  //       cameraYSpring.get(),
  //       cameraZSpring.get(),
  //     );
  //     camera.lookAt(markerRef.current.getWorldPosition(new THREE.Vector3()));
  //   }
  // });

  return (
    <>
      <group {...props} dispose={null}>
        <group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_computerScreen.geometry}
            material={materials.metalDark}
          />
          <mesh ref={screenRef} geometry={nodes.Mesh_computerScreen_1.geometry}>
            <meshStandardMaterial
              attach={"material"}
              map={texture}
              map-wrapT={THREE.RepeatWrapping}
              map-wrapS={THREE.ClampToEdgeWrapping}
              map-repeat={[0.13, 0.1]}
              map-flipY={false}
              map-offset={[-0.5, 0]}
            />
            <mesh
              ref={targetRef}
              visible={debug}
              position={[0.19, 0.175, -0.05]}
            >
              <boxGeometry args={[0.01, 0.01, 0.01]} />
              <meshBasicMaterial color="red" wireframe />
            </mesh>
          </mesh>
        </group>
      </group>
    </>
  );
}

useGLTF.preload("models/computerScreen.glb");
