/*
Semi-auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import type { JSX } from "react";
import * as THREE from "three";
import { type GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["computerMouse(Clone)"]: THREE.Mesh;
  };
  materials: {
    metalDark: THREE.MeshStandardMaterial;
  };
};

export default function Mouse(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "models/computerMouse.glb",
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["computerMouse(Clone)"].geometry}
        material={materials.metalDark}
      />
    </group>
  );
}

useGLTF.preload("models/computerMouse.glb");
