/*
Semi-auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import type { JSX } from "react";
import * as THREE from "three";
import { type GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_pottedPlant: THREE.Mesh;
    Mesh_pottedPlant_1: THREE.Mesh;
    plant: THREE.Mesh;
  };
  materials: {
    wood: THREE.MeshStandardMaterial;
    woodDark: THREE.MeshStandardMaterial;
    plant: THREE.MeshStandardMaterial;
  };
};

export function PottedPlant(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "models/pottedPlant.glb",
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group scale={2}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_pottedPlant.geometry}
          material={materials.wood}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_pottedPlant_1.geometry}
          material={materials.woodDark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.plant.geometry}
          material={materials.plant}
          position={[-0.053, 0.059, 0.06]}
          scale={0.5}
        />
      </group>
    </group>
  );
}

useGLTF.preload("models/pottedPlant.glb");
