/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import type { JSX } from "react";
import * as THREE from "three";
import { type GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    BézierCurve: THREE.Mesh;
  };
};

export function GithubLogo({
  material,
  ...props
}: {
  material?: THREE.MeshStandardMaterial;
} & Omit<JSX.IntrinsicElements["group"], "material">) {
  const { nodes } = useGLTF("/models/GithubLogo.glb") as unknown as GLTFResult;
  return (
    <group {...props}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BézierCurve.geometry}
        material={material || nodes.BézierCurve.material}
      />
    </group>
  );
}

useGLTF.preload("/models/GithubLogo.glb");
