/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import type { JSX } from "react";
import * as THREE from "three";
import { type GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Cube001: THREE.Mesh;
  };
};

export function LinkedinLogo({
  material,
  children,
  ...props
}: {
  material?: THREE.MeshStandardMaterial;
  children?: React.ReactNode;
} & Omit<JSX.IntrinsicElements["group"], "material">) {
  const { nodes } = useGLTF(
    "/models/LinkedinLogo.glb",
  ) as unknown as GLTFResult;
  return (
    <group {...props}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={material || nodes.Cube001.material}
      />
      {children}
    </group>
  );
}

useGLTF.preload("/models/LinkedinLogo.glb");
